-- ============================================================================
-- Veronum Bridge — daemon-side schema for the cloud relay.
--
-- This migration adds two tables to the existing Veronum Supabase project
-- (synpjcammfjebwsmtfpz). Both follow the conventions established in
-- veronum-overlay/supabase/migrations/001_shared_chat.sql:
--   - `veronum_` table prefix (coexists with the Tools-AI extension schema)
--   - pgcrypto for gen_random_uuid()
--   - `auth.uid()` returns the veronum_users.id when the request carries a
--     bridge-issued JWT (RLS gate)
--   - Realtime publication added explicitly per table
--   - Service role (used by Edge Functions) bypasses RLS as expected
--
-- Why two tables instead of one:
--   * `veronum_bridges` — one row per installed Mac. Pairing state +
--     metadata + last-seen heartbeat. Updated rarely.
--   * `veronum_bridge_dispatches` — one row per Claude/Cursor dispatch the
--     daemon handles. Drives Stripe usage metering (raw_cost_cents → meter
--     event api_cost_raw_cents) and powers a future "activity" surface.
--     Updated frequently — separated to keep the bridges table small.
--
-- Pairing flow (mirrors veronum-overlay's invite-token pattern):
--   1. Daemon launches for the first time, generates install_id (UUID v4)
--      stored in macOS keychain. Daemon does NOT yet have a user_id.
--   2. Daemon calls Edge Function `veronum-bridge/begin-pair` with its
--      install_id. The function INSERTs a row into veronum_bridges with
--      pair_code = 6-char alphanumeric and pair_code_expires_at = now()+5min,
--      and returns { pair_code }.
--   3. Daemon opens the user's browser to
--      https://www.thetoolswebsite.com/pair-bridge?code=<pair_code>
--   4. User is signed in (via existing AuthService). Page POSTs to
--      Edge Function `veronum-bridge/complete-pair` with { pair_code }.
--      The function calls public.veronum_bridge_pair(...) which atomically
--      sets user_id, paired_at, clears pair_code. Returns a Supabase JWT
--      bound to user_id that the daemon stores in keychain.
--   5. Daemon now uses that JWT for all Supabase reads (RLS-gated to the
--      user's own rows) and for joining the Realtime channel
--      `bridge:{user_id}`.
--
-- Channel naming for the relay:
--   Daemons publish to: bridge:{user_id} (broadcast events)
--   Browser sessions subscribe to the SAME channel name.
--   Both join via Realtime presence so each side knows the other is online.
-- ============================================================================

create extension if not exists "pgcrypto";

-- ─── veronum_bridges ────────────────────────────────────────────────────────
-- One row per installed Veronum Bridge.app. Created with user_id=null
-- (unpaired) by /begin-pair, then updated by /complete-pair when the user
-- confirms in the browser.
create table if not exists public.veronum_bridges (
  id uuid primary key default gen_random_uuid(),

  -- Daemon-generated UUID stored in macOS keychain on first run. Survives
  -- app reinstalls if the keychain entry isn't deleted. Used as the daemon
  -- identifier BEFORE a user is paired (the daemon has no user_id yet).
  install_id text unique not null,

  -- Set by /complete-pair. Null = unpaired (daemon shows "Pair this Mac"
  -- menu item). Cascade delete: if the user account is deleted, their
  -- bridges go too.
  user_id uuid references public.veronum_users(id) on delete cascade,

  -- One-time pair code generated by /begin-pair. Cleared by /complete-pair.
  -- Format: 6 alphanumeric chars, unambiguous (no 0/O/1/I). Short-lived.
  pair_code text,
  pair_code_expires_at timestamptz,

  -- When the pair completed.
  paired_at timestamptz,

  -- Self-reported daemon metadata for the "Devices" surface in settings.
  app_version text,        -- e.g. "0.1.0"
  os_version text,         -- e.g. "macOS 14.6.1"
  hostname text,           -- e.g. "dylans-laptop"

  -- Updated by veronum_bridge_heartbeat() while the daemon is connected
  -- to its Realtime channel. UI uses (now() - last_seen_at) to render an
  -- "online" / "offline" dot.
  last_seen_at timestamptz not null default now(),

  -- Audit / introspection.
  created_at timestamptz not null default now()
);

create index if not exists veronum_bridges_user_idx
  on public.veronum_bridges(user_id);

-- Partial unique on pair_code: enforces no two unpaired bridges share a
-- code, but allows multiple paired bridges (where pair_code is null).
create unique index if not exists veronum_bridges_pair_code_idx
  on public.veronum_bridges(pair_code)
  where pair_code is not null;

-- ─── veronum_bridge_dispatches ──────────────────────────────────────────────
-- One row per claude/cursor dispatch the daemon handles. Inserted by the
-- daemon AFTER each dispatch completes (success or fail). Drives:
--   * Stripe usage metering via raw_cost_cents → meter event
--   * A "recent activity" feed in the web UI
create table if not exists public.veronum_bridge_dispatches (
  id bigserial primary key,
  bridge_id uuid not null references public.veronum_bridges(id) on delete cascade,
  user_id uuid not null references public.veronum_users(id) on delete cascade,

  -- Which engine ran the dispatch.
  editor text not null check (editor in ('claude', 'cursor')),

  -- The Claude / Cursor session id ("cb524761-…"). Not a fk — the daemon
  -- doesn't sync session lists into Supabase.
  session_id text not null,

  -- The working directory the dispatch ran in.
  cwd text not null,

  -- Model selected by the user at dispatch time (e.g. "opus", "sonnet",
  -- "haiku" for Claude; "auto"/"gpt-5.5-medium" for Cursor).
  model text,

  -- For Claude only.
  effort text check (effort in ('low', 'medium', 'high', 'max')),

  -- Sizing.
  prompt_chars int not null default 0,
  response_chars int not null default 0,
  duration_ms int,

  -- Stripe metering — raw API cost in cents at Opus 4.7 estimated rates
  -- ($5/MTok input, $25/MTok output) regardless of which model actually
  -- ran. Mirrors the convention from veronum-overlay/renderer/src/stripe.ts.
  -- Multiplied by the user's tier markup (3x for PAYG, 2x for $25/mo
  -- overage) at the moment a meter event is emitted to Stripe.
  raw_cost_cents int not null default 0,

  -- True once the corresponding `api_cost_raw_cents` meter event has been
  -- sent to Stripe. Set by the billing-emitter background job. Lets us
  -- retry transient Stripe failures without double-billing.
  metered_billed boolean not null default false,

  -- A short error message if the dispatch failed (claude exited non-zero,
  -- session-busy, etc.). NULL on success.
  error_text text,

  started_at timestamptz not null default now(),
  finished_at timestamptz
);

create index if not exists veronum_bridge_dispatches_user_started_idx
  on public.veronum_bridge_dispatches(user_id, started_at desc);

create index if not exists veronum_bridge_dispatches_unbilled_idx
  on public.veronum_bridge_dispatches(metered_billed, finished_at)
  where metered_billed = false and finished_at is not null;

-- ─── Realtime publication ───────────────────────────────────────────────────
-- We DO NOT add veronum_bridges to the publication: the UI doesn't need to
-- react to row-level changes (heartbeat updates would be too noisy). The
-- web app uses the broadcast channel directly for live coordination.
--
-- veronum_bridge_dispatches IS added so a future "recent activity" panel
-- can subscribe and show dispatches as they complete.
do $$
begin
  alter publication supabase_realtime add table public.veronum_bridge_dispatches;
exception when duplicate_object then null;
end $$;

-- ─── Row-Level Security ─────────────────────────────────────────────────────
-- User can only see / modify their own bridges and dispatches. Edge
-- Functions use service role and bypass these policies.

alter table public.veronum_bridges enable row level security;
alter table public.veronum_bridge_dispatches enable row level security;

drop policy if exists "users see own bridges" on public.veronum_bridges;
create policy "users see own bridges"
  on public.veronum_bridges for select
  using (user_id = auth.uid());

drop policy if exists "users update own bridges" on public.veronum_bridges;
create policy "users update own bridges"
  on public.veronum_bridges for update
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

drop policy if exists "users delete own bridges" on public.veronum_bridges;
create policy "users delete own bridges"
  on public.veronum_bridges for delete
  using (user_id = auth.uid());

-- Note: INSERTs into veronum_bridges happen only via the Edge Function
-- /begin-pair, which runs as service role and bypasses RLS. No insert
-- policy is defined here on purpose (defense-in-depth — even an
-- authenticated user can't create bridges directly).

drop policy if exists "users see own dispatches" on public.veronum_bridge_dispatches;
create policy "users see own dispatches"
  on public.veronum_bridge_dispatches for select
  using (user_id = auth.uid());

-- Dispatch inserts also come from the daemon via service role. No insert
-- policy on purpose.

-- ─── Helper functions ──────────────────────────────────────────────────────

-- Generate a short, unambiguous pair code. Excludes O/0/I/1 to avoid the
-- "did the user type a zero or O" confusion.
create or replace function public.veronum_bridge_make_pair_code()
returns text
language sql
volatile
set search_path = public
as $$
  select string_agg(
    substr('ABCDEFGHJKLMNPQRSTUVWXYZ23456789', 1 + (random() * 31)::int, 1),
    ''
  )
  from generate_series(1, 6);
$$;

-- Begin a pair. Called by Edge Function /begin-pair (service role).
-- Returns the bridge row including the generated pair_code.
create or replace function public.veronum_bridge_begin_pair(
  p_install_id text,
  p_app_version text default null,
  p_os_version text default null,
  p_hostname text default null
)
returns public.veronum_bridges
language plpgsql
security definer
set search_path = public
as $$
declare
  v_pair_code text;
  v_bridge public.veronum_bridges;
begin
  v_pair_code := public.veronum_bridge_make_pair_code();

  insert into public.veronum_bridges (
    install_id, pair_code, pair_code_expires_at,
    app_version, os_version, hostname
  )
  values (
    p_install_id, v_pair_code, now() + interval '5 minutes',
    p_app_version, p_os_version, p_hostname
  )
  on conflict (install_id) do update
    set pair_code = excluded.pair_code,
        pair_code_expires_at = excluded.pair_code_expires_at,
        app_version = coalesce(excluded.app_version, public.veronum_bridges.app_version),
        os_version = coalesce(excluded.os_version, public.veronum_bridges.os_version),
        hostname = coalesce(excluded.hostname, public.veronum_bridges.hostname)
    -- but only allow re-pairing if not already paired (don't clobber
    -- an active pairing — user must explicitly "unpair" first).
    where public.veronum_bridges.user_id is null
  returning * into v_bridge;

  if v_bridge.id is null then
    raise exception 'bridge_already_paired';
  end if;

  return v_bridge;
end;
$$;

-- Complete a pair. Called by Edge Function /complete-pair (service role)
-- after verifying the calling browser is signed in as p_user_id.
-- Atomically transitions the bridge from unpaired → paired.
create or replace function public.veronum_bridge_complete_pair(
  p_pair_code text,
  p_user_id uuid
)
returns public.veronum_bridges
language plpgsql
security definer
set search_path = public
as $$
declare
  v_bridge public.veronum_bridges;
begin
  update public.veronum_bridges
  set user_id = p_user_id,
      paired_at = now(),
      pair_code = null,
      pair_code_expires_at = null,
      last_seen_at = now()
  where pair_code = p_pair_code
    and pair_code_expires_at > now()
    and user_id is null
  returning * into v_bridge;

  if v_bridge.id is null then
    raise exception 'invalid_or_expired_pair_code';
  end if;

  return v_bridge;
end;
$$;

-- Heartbeat. Called by the daemon every ~30s while connected to its
-- Realtime channel. Service-role-only (the daemon uses its JWT which has
-- RLS, but we still take install_id rather than relying on the JWT to
-- avoid coupling JWT renewal to heartbeat frequency).
create or replace function public.veronum_bridge_heartbeat(
  p_install_id text
)
returns void
language sql
security definer
set search_path = public
as $$
  update public.veronum_bridges
  set last_seen_at = now()
  where install_id = p_install_id
    and user_id is not null;
$$;

-- Sum unbilled raw_cost_cents per user. Called by the billing-emitter
-- background job that runs every N minutes and emits Stripe meter events.
-- After emission, the job updates metered_billed = true on the rows it
-- summed (separate UPDATE so we don't lose data if the Stripe call fails).
create or replace function public.veronum_bridge_unbilled_cents(
  p_user_id uuid
)
returns int
language sql
stable
set search_path = public
as $$
  select coalesce(sum(raw_cost_cents), 0)::int
  from public.veronum_bridge_dispatches
  where user_id = p_user_id
    and metered_billed = false
    and finished_at is not null;
$$;
